const statis = [
  {
    type: "PDF Files",
    total: 130,
    size: "6.5BG",
    icon: "fa-regular fa-file-pdf fa-lg",
    iconColor: "#0075ff",
  },
  {
    type: "Images",
    total: 115,
    size: "3.5BG",
    icon: "fa-regular fa-images fa-lg",
    iconColor: "#22c55e",
  },
  {
    type: "Word Files",
    total: 110,
    size: "3.2BG",
    icon: "fa-regular fa-file-word fa-lg",
    iconColor: "#f44336",
  },
  {
    type: "CSV Files",
    total: 99,
    size: "2.9BG",
    icon: "fa-solid fa-file-csv fa-lg",
    iconColor: "#f59e0b",
  },
];

const FilesData = [
  {
    name: "my-file.pdf",
    onwer: "Elzero",
    size: "5.5MB",
    date: "20/06/2020",
    icon: "./imgs/pdf.svg",
  },
  {
    name: "my-file.avi",
    onwer: "Admin",
    size: "12.5MB",
    date: "16/5/2021",
    icon: "./imgs/avi.svg",
  },
  {
    name: "my-file.eps",
    onwer: "Uploader",
    size: "2.7MB",
    date: "16/5/2021",
    icon: "./imgs/eps.svg",
  },
  {
    name: "my-file.psd",
    onwer: "Osama",
    size: "15.1MB",
    date: "16/5/2021",
    icon: "./imgs/psd.svg",
  },
  {
    name: "my-file.dll",
    onwer: "Coder",
    size: "2.2MB",
    date: "16/5/2021",
    icon: "./imgs/dll.svg",
  },
  {
    name: "my-file.png",
    onwer: "Designer",
    size: "1.1MB",
    date: "16/5/2021",
    icon: "./imgs/png.svg",
  },
  {
    name: "my-file.dll",
    onwer: "Coder",
    size: "2.2MB",
    date: "16/5/2021",
    icon: "./imgs/dll.svg",
  },
  {
    name: "my-file.png",
    onwer: "Designer",
    size: "1.1MB",
    date: "16/5/2021",
    icon: "./imgs/png.svg",
  },
  {
    name: "my-file.psd",
    onwer: "Osama",
    size: "15.1MB",
    date: "16/5/2021",
    icon: "./imgs/psd.svg",
  },
  {
    name: "my-file.pdf",
    onwer: "Elzero",
    size: "5.5MB",
    date: "20/06/2020",
    icon: "./imgs/pdf.svg",
  },
  {
    name: "my-file.avi",
    onwer: "Admin",
    size: "12.5MB",
    date: "16/5/2021",
    icon: "./imgs/avi.svg",
  },
  {
    name: "my-file.eps",
    onwer: "Uploader",
    size: "2.7MB",
    date: "16/5/2021",
    icon: "./imgs/eps.svg",
  },
  {
    name: "my-file.pdf",
    onwer: "Elzero",
    size: "5.5MB",
    date: "20/06/2020",
    icon: "./imgs/pdf.svg",
  },
  {
    name: "my-file.avi",
    onwer: "Admin",
    size: "12.5MB",
    date: "16/5/2021",
    icon: "./imgs/avi.svg",
  },
  {
    name: "my-file.eps",
    onwer: "Uploader",
    size: "2.7MB",
    date: "16/5/2021",
    icon: "./imgs/eps.svg",
  },
  {
    name: "my-file.psd",
    onwer: "Osama",
    size: "15.1MB",
    date: "16/5/2021",
    icon: "./imgs/psd.svg",
  },
  {
    name: "my-file.dll",
    onwer: "Coder",
    size: "2.2MB",
    date: "16/5/2021",
    icon: "./imgs/dll.svg",
  },
  {
    name: "my-file.png",
    onwer: "Designer",
    size: "1.1MB",
    date: "16/5/2021",
    icon: "./imgs/png.svg",
  },
  {
    name: "my-file.dll",
    onwer: "Coder",
    size: "2.2MB",
    date: "16/5/2021",
    icon: "./imgs/dll.svg",
  },
  {
    name: "my-file.png",
    onwer: "Designer",
    size: "1.1MB",
    date: "16/5/2021",
    icon: "./imgs/png.svg",
  },
  {
    name: "my-file.psd",
    onwer: "Osama",
    size: "15.1MB",
    date: "16/5/2021",
    icon: "./imgs/psd.svg",
  },
  {
    name: "my-file.pdf",
    onwer: "Elzero",
    size: "5.5MB",
    date: "20/06/2020",
    icon: "./imgs/pdf.svg",
  },
  {
    name: "my-file.avi",
    onwer: "Admin",
    size: "12.5MB",
    date: "16/5/2021",
    icon: "./imgs/avi.svg",
  },
  {
    name: "my-file.eps",
    onwer: "Uploader",
    size: "2.7MB",
    date: "16/5/2021",
    icon: "./imgs/eps.svg",
  },
];

export { FilesData, statis };
