const FriendsData = [
  {
    profile: "./imgs/friend-01.jpg",
    name: "Ahmed Nasser",
    job: "JavaScript Developer",
    friends: 99,
    projects: 15,
    articles: 25,
    joined: "02/10/2021",
    phone: "123456890",
    email: "mail@gamil.com",
    vip: true,
  },
  {
    profile: "./imgs/friend-02.jpg",
    name: "Omar Fathy",
    job: "Cloud Developer",
    friends: 30,
    projects: 11,
    articles: 12,
    joined: "02/08/2020",
    phone: "123456890",
    email: "mail@gamil.com",
    vip: false,
  },
  {
    profile: "./imgs/friend-03.jpg",
    name: "Omar Ahmed",
    job: "Mobile Developer",
    friends: 80,
    projects: 20,
    articles: 18,
    joined: "02/06/2020",
    phone: "123456890",
    email: "mail@gamil.com",
    vip: false,
  },
  {
    profile: "./imgs/friend-04.jpg",
    name: "Shady Nabil",
    job: "Back-End Developer",
    friends: 70,
    projects: 30,
    articles: 18,
    joined: "28/06/2020",
    phone: "123456890",
    email: "mail@gamil.com",
    vip: false,
  },
  {
    profile: "./imgs/friend-05.jpg",
    name: "Mohamed Ibrahim",
    job: "Mohamed Ibrahim",
    friends: 80,
    projects: 30,
    articles: 18,
    joined: "28/06/2020",
    phone: "123456890",
    email: "mail@gamil.com",
    vip: false,
  },
  {
    profile: "./imgs/friend-04.jpg",
    name: "Amr Hendawy",
    job: "Back-End Developer",
    friends: 70,
    projects: 30,
    articles: 18,
    joined: "28/06/2020",
    phone: "123456890",
    email: "mail@gamil.com",
    vip: false,
  },
  {
    profile: "./imgs/friend-02.jpg",
    name: "Mahmoud Adel",
    job: "Cloud Developer",
    friends: 30,
    projects: 11,
    articles: 12,
    joined: "02/08/2020",
    phone: "123456890",
    email: "mail@gamil.com",
    vip: false,
  },
  {
    profile: "./imgs/friend-05.jpg",
    name: "Ahmed Abuzaid",
    job: "Ahmed Abuzaid",
    friends: 80,
    projects: 30,
    articles: 18,
    joined: "28/06/2020",
    phone: "123456890",
    email: "mail@gamil.com",
    vip: true,
  },
  {
    profile: "./imgs/friend-01.jpg",
    name: "Gareeb Elshiekh",
    job: "JavaScript Developer",
    friends: 99,
    projects: 15,
    articles: 25,
    joined: "02/10/2021",
    phone: "123456890",
    email: "mail@gamil.com",
    vip: true,
  },
  {
    profile: "./imgs/friend-03.jpg",
    name: "Hamza",
    job: "Front-End Developer",
    friends: 80,
    projects: 20,
    articles: 18,
    joined: "02/06/2020",
    phone: "123456890",
    email: "mail@gamil.com",
    vip: false,
  },
];

export default FriendsData;
