const PorjectsData = [
  {
    name: "Elzero Dashboard",
    description: "Elzero Dashboard Project Design And Programming And Hosting",
    team: [
      "./imgs/team-01.png",
      "./imgs/team-02.png",
      "./imgs/team-03.png",
      "./imgs/team-04.png",
      "./imgs/team-05.png",
    ],
    skills: ["Programming", "Design", "Hosting", "Marketing"],
    progress: 48,
    price: 2500,
    date: "15/10/2021",
  },
  {
    name: "Academy Portal",
    description: "Academy Portal Project Design And Programming",
    team: ["./imgs/team-01.png", "./imgs/team-02.png", "./imgs/team-03.png"],
    skills: ["Programming", "Design"],
    progress: 80,
    price: 1800,
    date: "15/6/2022",
  },
  {
    name: "Chatting Application",
    description: "Chatting Application Project Design",
    team: ["./imgs/team-01.png", "./imgs/team-02.png", "./imgs/team-03.png"],
    skills: ["Design"],
    progress: 100,
    price: 950,
    date: "15/6/2022",
  },
  {
    name: "Ahmed Dashboard",
    description: "Ahmed Dashboard Project Design And Programming And Hosting",
    team: [
      "./imgs/team-01.png",
      "./imgs/team-02.png",
      "./imgs/team-03.png",
      "./imgs/team-04.png",
    ],
    skills: ["Programming", "Design", "Hosting", "Marketing"],
    progress: 60,
    price: 1700,
    date: "15/6/2022",
  },
  {
    name: "Ahmed Portal",
    description: "Ahmed Portal Project Design And Programming",
    team: ["./imgs/team-01.png", "./imgs/team-02.png", "./imgs/team-03.png"],
    skills: ["Programming", "Design"],
    progress: 85,
    price: 850,
    date: "15/6/2022",
  },
  {
    name: "Mohamed Application",
    description: "Mohamed Application Project Design",
    team: ["./imgs/team-01.png", "./imgs/team-02.png", "./imgs/team-03.png"],
    skills: ["Design"],
    progress: 35,
    price: 950,
    date: "15/6/2022",
  },
  {
    name: "Mohamed Dashboard",
    description: "Mohamed Dashboard Project Design And Programming And Hosting",
    team: [
      "./imgs/team-01.png",
      "./imgs/team-02.png",
      "./imgs/team-03.png",
      "./imgs/team-04.png",
    ],
    skills: ["Programming", "Design", "Hosting", "Marketing"],
    progress: 65,
    price: 1950,
    date: "15/6/2022",
  },
  {
    name: "Mohamed Portal",
    description: "Mohamed Portal Project Design And Programming",
    team: ["./imgs/team-01.png", "./imgs/team-02.png", "./imgs/team-03.png"],
    skills: ["Programming", "Design"],
    progress: 60,
    price: 1650,
    date: "15/6/2022",
  },
  {
    name: "Ahmed  Application",
    description: "Ahmed  Application Project Design",
    team: ["./imgs/team-01.png", "./imgs/team-02.png", "./imgs/team-03.png"],
    skills: ["Design"],
    progress: 90,
    price: 950,
    date: "15/6/2022",
  },
];

export default PorjectsData;
